# Generated by Django 5.2.3 on 2025-07-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_following'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Following',
            new_name='Follow',
        ),
    ]
