# Generated by Django 5.2.3 on 2025-07-10 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_rename_following_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
